"""empty message

Revision ID: 050ab124a75c
Revises: a668073ebe58
Create Date: 2021-02-23 17:31:39.393414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050ab124a75c'
down_revision = 'a668073ebe58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facilities')
    # ### end Alembic commands ###
