"""removed bad history

Revision ID: 503769b63fba
Revises: 
Create Date: 2021-03-03 14:57:13.765378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503769b63fba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=10), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('open_registration', sa.Boolean(), nullable=False),
    sa.Column('default_account_expiry_time', sa.Integer(), nullable=True),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name')
    )
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_on', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'tenant_id')
    )
    op.create_table('availabilities',
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('mondayStart', sa.Integer(), nullable=True),
    sa.Column('mondayEnd', sa.Integer(), nullable=True),
    sa.Column('tuesdayStart', sa.Integer(), nullable=True),
    sa.Column('tuesdayEnd', sa.Integer(), nullable=True),
    sa.Column('wednesdayStart', sa.Integer(), nullable=True),
    sa.Column('wednesdayEnd', sa.Integer(), nullable=True),
    sa.Column('thursdayStart', sa.Integer(), nullable=True),
    sa.Column('thursdayEnd', sa.Integer(), nullable=True),
    sa.Column('fridayStart', sa.Integer(), nullable=True),
    sa.Column('fridayEnd', sa.Integer(), nullable=True),
    sa.Column('saturdayStart', sa.Integer(), nullable=True),
    sa.Column('saturdayEnd', sa.Integer(), nullable=True),
    sa.Column('sundayStart', sa.Integer(), nullable=True),
    sa.Column('sundayEnd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('facility_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availabilities')
    op.drop_table('users')
    op.drop_table('facilities')
    op.drop_table('tenants')
    # ### end Alembic commands ###
