"""added new fields to Tenant

Revision ID: c3476fc6578d
Revises: 8ba363ba5ecb
Create Date: 2021-02-27 16:32:27.038621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3476fc6578d'
down_revision = '8ba363ba5ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_account_expiry_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('statement', sa.String(), nullable=True))
        batch_op.alter_column('open_registration',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('open_registration',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('statement')
        batch_op.drop_column('phone')
        batch_op.drop_column('location')
        batch_op.drop_column('description')
        batch_op.drop_column('default_account_expiry_time')

    # ### end Alembic commands ###
