name: pipeline

on: push
    
jobs:
  test-suite:
    runs-on: ubuntu-latest

    services: # adding postgres to flow file for testing
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testing
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 2
        ports:
          # Maps tcp port 5432 on service to host
          - 5432:5432
  
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python v3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ -f rest-api/src/requirements.txt ]]; then pip install -r rest_api/src/requirements.txt; fi
          
      - name: run unittest
        run: python -m unittest discover rest_api/src/
        env:
          FLASK_APP: main.py
          FLASK_ENV: testing  
        