name: pipeline

on: push
    
jobs:
  test-suite:
    runs-on: ubuntu-latest    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python v3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ -f rest-api/src/requirements.txt ]]; then pip install -r rest-api/src/requirements.txt; fi
          
      - name: run unittest
        run: python -m unittest discover rest-api/src/